from aiogram.utils.media_group import MediaGroupBuilder
from aiogram.types import FSInputFile

album_albebra = MediaGroupBuilder()
album_albebra.add_photo(type="photo", media=FSInputFile("file/15.png"))
album_albebra.add_photo(type="photo", media=FSInputFile("file/16.png"))
album_albebra.add_photo(type="photo", media=FSInputFile("file/17.png"))
album_albebra.add_photo(type="photo", media=FSInputFile("file/18.png"))

album_geomerish = MediaGroupBuilder()
album_geomerish.add_photo(type="photo", media=FSInputFile("file/19.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/20.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/21.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/22.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/23.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/24.png"))
album_geomerish.add_photo(type="photo", media=FSInputFile("file/25.png"))

album_fisish = MediaGroupBuilder()
album_fisish.add_photo(type="photo", media=FSInputFile("file/26.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/27.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/28.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/30.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/31.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/32.png"))
album_fisish.add_photo(type="photo", media=FSInputFile("file/33.png"))

album_rusish = MediaGroupBuilder()
album_rusish.add_photo(type="photo", media=FSInputFile("file/41.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/42.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/43.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/45.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/46.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/47.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/48.png"))
album_rusish.add_photo(type="photo", media=FSInputFile("file/49.png"))